import { chromium } from 'playwright-core'
const browser = await chromium.launch({ executablePath: '/usr/local/bin/chromium', args: ['--no-sandbox'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('file:///data/alisa4/index.html')
await page.waitForTimeout(11000)
await page.evaluate(() => document.getElementById('menuBtn').click())
await page.waitForTimeout(900)
await page.evaluate(() => document.querySelector('.mpi[data-sec="ct"]').click())
await page.waitForTimeout(2000)
const check = await page.evaluate(() => Array.from(document.querySelectorAll('.lcard')).map(c => { const img = c.querySelector('.lc-img img'); return { t: c.querySelector('.lc-title').textContent, img: !!img, ok: img ? img.naturalWidth > 0 : null } }))
console.log('ru', JSON.stringify(check))
await page.screenshot({ path: '/data/qa-p1.png' })
await page.evaluate(() => document.getElementById('lang').click())
await page.waitForTimeout(4000)
const checkEn = await page.evaluate(() => Array.from(document.querySelectorAll('.lcard')).map(c => { const img = c.querySelector('.lc-img img'); return { t: c.querySelector('.lc-title').textContent, img: !!img } }))
console.log('en', JSON.stringify(checkEn))
await page.close()
const m = await browser.newPage({ viewport: { width: 390, height: 844 } })
await m.goto('file:///data/alisa4/index.html')
await m.waitForTimeout(11000)
await m.evaluate(() => document.getElementById('menuBtn').click())
await m.waitForTimeout(900)
await m.evaluate(() => document.querySelector('.mpi[data-sec="ct"]').click())
await m.waitForTimeout(2000)
await m.screenshot({ path: '/data/qa-p2.png' })
await browser.close()
